#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE=".env.local"

FIX="tests/fixtures"
CAPTURE="scripts/capture-us-fixtures.sh"

banner "Ground Truth: the four things only you can do"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "EPA AQS: historical air monitor key"
say "AQS gives out keys by email. You request one by visiting a URL with your"
say "address in it, and the key arrives in your inbox a moment later."
say ""
ask AQS_EMAIL "Which email should the key go to?"
if [[ -n "${AQS_EMAIL:-}" ]]; then
  open_url "https://aqs.epa.gov/data/api/signup?email=${AQS_EMAIL}"
  step "The page returns a short JSON body saying the request was accepted."
  step "Check that inbox. The key is a word-like string, not a long hash."
  note "Nothing is emailed by this script. The browser request does it."
  ask_secret AQS_KEY "Paste the key from the email:"
  write_env AQS_EMAIL "$AQS_EMAIL"
  write_env AQS_KEY "${AQS_KEY:-}"
  note "AQS allows 10 requests a minute and asks for 5 seconds between calls."
  note "Its data lags collection by six months or more, which the report says."
else
  SKIPPED+=("EPA AQS key: no email given")
  warn "skipped AQS"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "AirNow: current conditions key"
say "AirNow needs a real account, not just an email. The form wants a username"
say "and a password as well, so keep a password manager open."
open_url "https://docs.airnowapi.org/account/request/"
step "Fill first name, last name, username, password, email and phone."
step "The password must be 8 to 20 characters with a lower case letter, an"
step "upper case letter, a number and a symbol."
step "Tick the box agreeing to the EPA AirNow data use guidelines, then submit."
pause "Submitted the form?"
open_url "https://docs.airnowapi.org/account/list/"
step "Log in if it asks. Your key is listed here, and also in the top right"
step "corner of the Web Services page."
ask_secret AIRNOW_KEY "Paste the AirNow key:"
if [[ -n "${AIRNOW_KEY:-}" ]]; then
  write_env AIRNOW_KEY "$AIRNOW_KEY"
else
  SKIPPED+=("AirNow key")
  warn "skipped AirNow"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "ECHO and FEMA: capture from a US-reachable host"
say "Two hosts refuse connections from this machine. echodata.epa.gov resets"
say "the stream, and hazards.fema.gov resets the TLS handshake. Neither is a"
say "rate limit and no key would help. The bytes have to come from somewhere"
say "that can reach them."
say ""
say "A capture script is ready at:"
note "  $CAPTURE"
say ""
say "Run it in whichever of these is easiest:"
step "This machine with a US VPN turned on. Simplest if you have one."
step "Any US cloud box you can ssh to, then copy $FIX back."
step "A GitHub Actions runner, if you give this repo a remote."
say ""
note "It writes only to $FIX/echo and $FIX/fema and touches nothing else."
pause "Run it now, then come back here."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Check what landed"
missing=0
for f in \
  "$FIX/echo/facilities-5mi-houston.json" \
  "$FIX/echo/facility-detail.json" \
  "$FIX/fema/nfhl-zone-ae-pasadena.json" \
  "$FIX/fema/nfhl-minimal-hazard.json"
do
  if [[ -s "$f" ]]; then
    printf '  %s✓%s %s (%s bytes)\n' "$GREEN" "$RESET" "$f" "$(wc -c <"$f" | tr -d ' ')"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$f"
    missing=$((missing + 1))
  fi
done
if (( missing > 0 )); then
  warn "$missing capture(s) missing, so those adapters stay on a derived schema"
  SKIPPED+=("$missing US-only fixture(s): re-run $CAPTURE from a US host")
else
  say ""
  say "All four landed. ECHO and the authoritative FEMA layer can now be built"
  say "against real bytes instead of EPA's published column list."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Prove it works"
say "Running the checks so you can see the state you left the repo in."
say ""
if pnpm verify; then
  say ""
  printf '  %s✓ verify green%s\n' "$GREEN" "$RESET"
else
  warn "verify failed, which is worth reading before you trust anything above"
fi

finish
