export {
	coalesce,
	fieldsOf,
	fromQuery,
	haversine,
	isSealed,
	isSourced,
	KERNEL_VERSION,
	ReaderInvariant,
	seal,
	UnbrandedValue,
	urlFrom,
} from "./sourced";
export type {
	AbsentProvenance,
	AdapterVersion,
	ComputationInput,
	ComputationProvenance,
	Fetched,
	FieldProvenance,
	FieldReader,
	Formula,
	GeoPoint,
	JsonObject,
	JsonValue,
	KeysWhere,
	PayloadRef,
	Picked,
	PickSpec,
	Provenance,
	QueryProvenance,
	Sealed,
	Sourced,
	TransformName,
} from "./sourced";

export { AGENCY, emptyStore, KINDS, recordId, sameId, storeOf } from "./records";
export type {
	Built,
	EchoProgramStatuses,
	EvidenceRecord,
	EvidenceStore,
	FemaFloodZoneRecord,
	FrsProgramInterest,
	GeocodeMatch,
	Kind,
	RecordId,
	RecordOf,
	SemsSiteRecord,
	SourceId,
	SourceOf,
	StatusRowOutcome,
} from "./records";

export { defineTemplate, fallback, isSlotRef, km, sentence } from "./templates";
export type {
	AnyRef,
	Clause,
	DisplayFormat,
	FieldRef,
	GroupSubject,
	NumericKeys,
	OriginSubject,
	Reported,
	SectionSubject,
	SlotKeys,
	SlotRef,
	SourcedKeys,
	SourceSubject,
	SubjectKey,
	SubjectOf,
	Template,
	TemplateRegistry,
	WideScope,
} from "./templates";

export { defineSection, formatValue, KindMismatch, render, renderAll, sectionOrdering, trace, verify } from "./sentence";
export type {
	GroupPlacement,
	GroupTrace,
	OriginPlacement,
	OriginTrace,
	Placement,
	RecordPlacement,
	RecordTrace,
	SectionFilter,
	SectionPlacement,
	SectionSpec,
	SectionTrace,
	Sentence,
	SentenceSubject,
	SourcePlacement,
	SourceTrace,
	Span,
	Trace,
	ValueTrace,
} from "./sentence";

export {
	complete,
	DEFAULT_POLICY,
	NO_DATA_NOTE,
	NoPayload,
	runSource,
	runSources,
	SourceFailure,
	storeOfSources,
	unavailableOf,
} from "./source";
export type {
	Adapter,
	FailureCause,
	Locus,
	SourceIo,
	SourceMap,
	SourceOutcome,
	SourcePolicy,
	SourceUnavailable,
} from "./source";
